#!/bin/bash
#
# taskfactory		Start up the taskfactory service
#
# chkconfig: 2345 95 5
# description: taskfactory converts uploaded task lists to clickwork tasks
#              
#
# processname: taskfactory
# pidfile: /var/run/taskfactory/pid

### BEGIN INIT INFO
# Provides: taskfactory
# Required-Start: $local_fs $network $syslog
# Required-Stop: $local_fs $syslog
# Should-Start: $syslog
# Should-Stop: $network $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start up the taskfactory service
# Description:       taskfactory converts uploaded task lists to clickwork tasks
#		     
### END INIT INFO

export PYTHONPATH=/usr/local/lib/python2.6/dist-packages/

# source function library
. /etc/rc.d/init.d/functions

# pull in sysconfig settings
[ -f /etc/sysconfig/taskfactory ] && . /etc/sysconfig/taskfactory

RETVAL=0
prog="taskfactory.py"
lockfile=/var/lock/subsys/$prog

# Some functions to make the below more readable
TASKFACTORY=/usr/lib/clickwork/main/utils/taskfactory.py
PID_FILE=/var/run/taskfactory/pid

runlevel=$(set -- $(runlevel); eval "echo \$$#" )

start()
{
	[ -x $TASKFACTORY ] || exit 5
	echo -n $"Starting $prog: "
	$TASKFACTORY $OPTIONS && success || failure
	RETVAL=$?
	[ $RETVAL -eq 0 ] && touch $lockfile
	echo
	return $RETVAL
}

stop()
{
	echo -n $"Stopping $prog: "
	kill `cat $PID_FILE`
	[ $RETVAL -eq 0 ] && rm -f $lockfile
	echo
}

restart() {
	stop
	start
}

rh_status() {
	status -p $PID_FILE taskfactory.py
}

rh_status_q() {
	rh_status >/dev/null 2>&1
}

case "$1" in
	start)
		rh_status_q && exit 0
		echo starting...
		start
		;;
	stop)
		if ! rh_status_q; then
			rm -f $lockfile
			exit 0
		fi
		stop
		;;
	restart)
		restart
		;;
	status)
		rh_status
		RETVAL=$?
		if [ $RETVAL -eq 3 -a -f $lockfile ] ; then
			RETVAL=2
		fi
		;;
	*)
		echo $"Usage: $0 {start|stop|restart|status}"
		RETVAL=2
esac
exit $RETVAL
